[package]
name = "api-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["net", "rt-multi-thread"] }